version: '3.8'

services:
  # Snapifit AI 应用
  snapfit-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - KEY_ENCRYPTION_SECRET=${KEY_ENCRYPTION_SECRET}
      - LINUX_DO_CLIENT_ID=${LINUX_DO_CLIENT_ID}
      - LINUX_DO_CLIENT_SECRET=${LINUX_DO_CLIENT_SECRET}
      - LINUX_DO_REDIRECT_URI=${LINUX_DO_REDIRECT_URI:-http://localhost:3000/api/auth/callback/linux-do}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DEFAULT_OPENAI_API_KEY=${DEFAULT_OPENAI_API_KEY}
      - DEFAULT_OPENAI_BASE_URL=${DEFAULT_OPENAI_BASE_URL:-https://api.openai.com}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - snapfit-network

networks:
  snapfit-network:
    driver: bridge
